var weaponreforge = [
    {
        name: "None",
        tier: 0,
        value: 0,
        damage: 0,
        speed: 0,
        crit: 0,
        mana: 0,
        size: 0,
        velocity: 0,
        knockback: 0,
    },
    {
        name: "Legendary",
        tier: 2,
        value: 2.0985,
        damage: .15,
        speed: .1,
        crit: .05,
        mana: 0,
        size: .1,
        velocity: 0,
        knockback: .15,
    },
    {
        name: "Unreal",
        tier: 2,
        value: 2.0985,
        damage: .15,
        speed: 0.1,
        crit: 0.05,
        mana: 0,
        size: 0,
        velocity: 0.1,
        knockback: 0.15,
    },
    {
        name: "Mythical",
        tier: 2,
        value: 2.0985,
        damage: 0.15,
        speed: 0.1,
        crit: 0.5,
        mana: -0.1,
        size: 0,
        velocity: 0,
        knockback: 0.15,
    },
    {
        name: "Godly",
        tier: 2,
        value: 1.1163,
        damage: 0.15,
        speed: 0,
        crit: 0.5,
        mana: 0,
        size: 0,
        velocity: 0,
        knockback: 0.15,
    },
    {
        name: "Ruthless",
        tier: 1,
        value: 0.1278,
        damage: 0.18,
        speed: 0,
        crit: 0,
        mana: 0,
        size: 0,
        velocity: 0,
        knockback: -0.1,
    }
]


var accessoryreforge = [
    {
        name: "None",
        tier: 0,
        value: 0,
        defense: 0,
        damage: 0,
        crit: 0,
        meleeSpeed: 0,
        moveSpeed: 0,
        mana: 0
    },
    {
        name: "Warding",
        tier: 2,
        value: 0.44,
        defense: 4,
        damage: 0,
        crit: 0,
        meleeSpeed: 0,
        moveSpeed: 0,
        mana: 0
    },
    {
        name: "Menacing",
        tier: 2,
        value: 0.44,
        defense: 0,
        damage: 0,
        crit: 0,
        meleeSpeed: 0,
        moveSpeed: 0,
        mana: 0
    },
    {
        name: "Lucky",
        tier: 2,
        value: 0.44,
        defense: 0,
        damage: 0.4,
        crit: 0,
        meleeSpeed: 0,
        moveSpeed: 0,
        mana: 0
    },
    {
        name: "Violent",
        tier: 2,
        value: 0.44,
        defense: 4,
        damage: 0,
        crit: 0.4,
        meleeSpeed: 0,
        moveSpeed: 0,
        mana: 0
    },
    {
        name: "Warding",
        tier: 2,
        value: 0.44,
        defense: 4,
        damage: 0,
        crit: 0,
        meleeSpeed: 0,
        moveSpeed: 0,
        mana: 0
    },
    {
        name: "Warding",
        tier: 2,
        value: 0.44,
        defense: 4,
        damage: 0,
        crit: 0,
        meleeSpeed: 0,
        moveSpeed: 0,
        mana: 0
    }
]